name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  reComuputer-R100x-64-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: before Build
        run: |
          sudo apt-get update
          sudo apt-get -y install dialog coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools \
            libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz xxd kmod binfmt-support
      
      - name: Add prerun.sh
        run: |
          cat > stage4a/prerun.sh <<-EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
          chmod +x stage4a/prerun.sh
          chmod +x stage4a/00-seeed-dtoverlays/*.sh

      
      - name: Getting parameter configuration
        run: |
          # $(grep 'image-name=' reComputer-R100x-64-config | sed 's/^image-name=//')
          SEEED_DEV_NAME=reComputer-R100x
          GIT_MODULE='https://github.com/Seeed-Studio/seeed-linux-dtoverlays.git -b master --depth=1'
      
      - name: Build pi-gen with stage4a
        uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: 'Raspbian-reComputer-R100x-arm64'
          compression: none
          enable-ssh: 1
          wpa-country: CN
          keyboard-keymap: us
          stage-list: stage0 stage1 stage2 stage4a
          verbose-output: true

      - name: Upload pi-gen image
        uses: actions/upload-artifact@v3
        with:
          name: reComuputer-R100x-64-image
          path: ${{ steps.build.outputs.image-path }}