name: Build pi-gen image

on:
  workflow_dispatch:
    inputs:
      dev_name:
        description: 'Name of device'
        required: true
        default: 'pi'
        type: choice
        options:
          - raspberrypi
          - reComputer-R100x
          - reTerminal
          - reTerminal-plus
      pi-gen-version:
        description: 'This can both be a branch or tag name known in the pi-gen repository.'
        required: true
        default: 'arm64'
        type: string
      enable-ssh:
        description: 'Enable SSH server'
        required: true
        default: "1"
        type: choice
        options:
          - 1
          - 0
      stage-list:
        description: 'List of stage name to execute in given order.'
        required: true
        default: 'stage0 stage1 stage2 stage3 stage4 stage4a'
        type: string
      wpa-country:
        description: 'Set the country code for WPA'
        required: true
        default: 'CN'
        type: string
      keyboard-keymap:
        description: 'Set the keyboard keymap'
        required: true
        default: 'us'
        type: string
      disable-first-boot-user-rename:
        description: 'Disable the renaming of the first user during the first boot.'
        required: true
        default: "0"
        type: choice
        options:
          - 1
          - 0
      username:
        description: 'Username for the image'
        required: true
        default: 'pi'
        type: string
      password:
        description: 'Password for the image'
        required: true
        default: 'raspberry'
        type: string
      verbose-output:
        description: 'Enable verbose output'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

env:
  EXPORT_LAST_STAGE_ONLY: true
  PI_GEN_DIR: 'pi-gen'
  
jobs:
  pi-gen-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: update README.md
        run: | 
         python3 update_readme.py 'raspberrypi-arm64' 'pi'  'raspberry' '1' 'stage0 stage1 stage2' 'https://github.com/is-qian/pi-gen/actions/runs/9249233565/artifacts/1539663169'

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -a -m 'update README.md'
          git push 