name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  pi-gen-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build pi-gen with test-stage
        uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test
          stage-list: stage0 stage1 stage3 stage4 stage4a
          verbose-output: true

      - name: Upload pi-gen image
        uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}