name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  pi-gen-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p test-stage/package-test &&
          {
          cat > test-stage/package-test/00-run-chroot.sh <<-EOF
          #!/bin/bash
          MODULE_PATH=/tmp/seeed-linux-dtoverlays
          apt-get update
          apt-get -y install dialog coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz xxd kmod binfmt-support
          git clone https://github.com/Seeed-Studio/seeed-linux-dtoverlays.git -b master --depth=1
          cd seeed-linux-dtoverlays
          ls -l
          ./scripts/reTerminal.sh --device reComputer-R100x
          EOF
          } &&
          chmod +x test-stage/package-test/00-run-chroot.sh &&
          echo "nodejs" > test-stage/package-test/01-packages &&
          {
          cat > test-stage/prerun.sh <<-EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
          } &&
          chmod +x test-stage/prerun.sh
      - name: Build pi-gen with test-stage
        uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test
          stage-list: stage0 stage1 stage2 stage3 stage4 ./stage4a
          verbose-output: true

      - name: Upload pi-gen image
        uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}