name: Build and upload image
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  pi-gen-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "nodejs" > stage4a/package-test/01-packages &&
          {
          cat > stage4a/prerun.sh <<-EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
          } &&
          chmod +x stage4a/prerun.sh
      - name: Build pi-gen with stage4a
        uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: test
          stage-list: stage0 stage1 stage2 stage4a
          verbose-output: true

      - name: Upload pi-gen image
        uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}